### ISSUE TITLE
The ReRoute configuration object is too large.(idea on solving this?)

### ISSUE THREAD

**Issue by david0718** [TomPallister/Ocelot#106]
Hi guy
I have An idea on this. I came to this idea from java platform api management tool,though I am a .net developer and fan.
The idea is that how about we put reroute config into a web application, who is responsible to manage apis towards projects, modules, so we could manage apis with category, and easily test all envs,like dev, stage and prod.
Thanks
David

**Comment by TomPallister** [comment]
@david0718 I'm not quite sure what you mean.

At the moment the Ocelot configuration is a flat file (JSON) that gets parsed and turned into a big config object in memory. 

You can change this object at runtime using the [http administration API.](https://github.com/TomPallister/Ocelot/wiki/Administration)

You could make a web application that calls into the admin api to manage config, is this what you mean?

**Comment by david0718** [comment]
Hi Tom
Yes, I think a web application could be a good way to manage this.

Some user story considered:
1.Admin could be login to the application.
2.Basic settings, permission(using orchard or abp)
3.Could create project, could create modules under project(or category),then create api route data.
4.api denifinition could be added for each item,mock data could be returned for each api.
This is what I mean. Very appreciated you could reply on this.

Thanks
David

**Comment by TomPallister** [comment]
Hi @david0718 ,

I have thought about building an administration UI (we already have an API) but don't have the time yet!

**Comment by jzarob** [comment]
What if we added support for something like Swagger, so downstream services could automatically register all their endpoints as ReRoutes instead of having to manually specify them?

**Comment by TomPallister** [comment]
@jzarob how would you envisage this working? I don't have much experience with swagger!!

**Comment by jzarob** [comment]
I would say add a config option that contains a list of downstream services. Each element in the list would contain default reroute configuration for all of the routes it registers, and a url to the swagger endpoint supported by the service. 

You can checkout an example of the docs generated by swagger here: 
[Swagger Editor](http://editor.swagger.io/)

**Comment by TomPallister** [comment]
@jzarob this seems like a good idea..I have added it to the backlog.

Thanks for your interest!

**Comment by urdeveloper** [comment]
I think Express-Gateway has a very interesting configuration structure you might get some idea from. Basically There are Api Endpoints (upstream) and Service Endpoints (downstream) that you define independently. Then you define a set of pipelines that connects the dots. A pipeline is a sequence of middlewares (they call it policies) that are configured in the pipeline. An example:

```yaml
    http:
      port: 8080
    admin:
      port: 9876
      hostname: 0.0.0.0
    apiEndpoints:
      api:
        host: '*'
        paths: '/ip'
    serviceEndpoints:
      httpbin:
        url: 'https://httpbin.org'
    policies:
      - basic-auth
      - cors
      - expression
      - key-auth
      - log
      - oauth2
      - proxy
      - rate-limit
    pipelines:
      default:
        apiEndpoints:
          - api
        policies:
          - key-auth:
          - proxy:
              - action:
                  serviceEndpoint: httpbin
                  changeOrigin: true
```

The above configuration says, for "/ip" upstream path use key-auth and proxy middlewares. The proxy middleware here is responsible for passing down the request to httpbin.org (downstream).

You can find the configuration reference here: http://www.express-gateway.io/docs/configuration/gateway.config.yml/

I hope you'll it helpful.
